site_name: Mojo Library Docs
docs_dir: docs
site_dir: site

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.indexes
    - navigation.expand
    - version-selector

extra:
  version:
    provider: mike

nav:
  - Home: index.md
  - Topic1: topic1.md

plugins:
  - i18n:
      docs_structure: suffix
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - locale: ja
          name: 日本語
          build: true
          nav_translations:
            Home: ホーム
            Topic1: トピック1
